# Source: jx-verify/templates/job-role.yaml
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: jx-verify-gc-jobs
  annotations:
    meta.helm.sh/release-name: 'jx-verify'
  namespace: jx-production
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
      - delete
