apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  creationTimestamp: null
  labels:
    owner: bussrrajeshnayak
    provider: github
    repository: golang-http-01
    gitops.jenkins-x.io/pipeline: 'namespaces'
  name: bussrrajeshnayak-golang-http-01
  namespace: jx
spec:
  httpCloneURL: https://github.com/bussrrajeshnayak/golang-http-01.git
  org: bussrrajeshnayak
  provider: https://github.com
  providerKind: github
  providerName: github
  repo: golang-http-01
  scheduler:
    kind: ""
    name: in-repo
  url: https://github.com/bussrrajeshnayak/golang-http-01
