# Source: jx-verify/templates/job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: jx-verify-gc-jobs-ncqp7
  annotations:
    kapp.k14s.io/disable-wait: ""
    meta.helm.sh/release-name: 'jx-verify'
  labels:
    app: jx-verify-gc-jobs-ljugy
    release: jx-verify
    gitops.jenkins-x.io/pipeline: 'namespaces'
  namespace: jx-staging
spec:
  backoffLimit: 1
  completions: 1
  parallelism: 1
  template:
    metadata:
    spec:
      containers:
        - command:
            - jx-verify
            - pods
          env:
            - name: XDG_CONFIG_HOME
              value: /home
          image: ghcr.io/jenkins-x/jx-verify:0.1.6
          imagePullPolicy: IfNotPresent
          name: job
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      serviceAccountName: jx-verify-gc-jobs
